### ISSUE TITLE
CT Cannot read properties of undefined (reading 'minus')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#14]
```
my-solar-system : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at c (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:1523016)
at s.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:14168)
at C.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:117181)
at pD.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:1501397)
at mD.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:1458781)
at mD.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:1458861)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:1437821)
at Co.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:581102)
at nC.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:1446226)
at nC.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661319781935%7D&fuzz&memoryLimit=1000:882:1446164)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 5:50:03 PM

----------------------------------

my-solar-system : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661333828026%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at minus (EllipticalOrbitNode.ts:138:70)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (EllipticalOrbit.ts:117:24)
at update (CommonModel.ts:146:16)
at update (CommonModel.ts:151:9)
at step (Sim.ts:443:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1018:30)
at stepSimulation (Sim.ts:1008:11)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 5:50:03 PM

----------------------------------

my-solar-system : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661318287611%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at minus (EllipticalOrbitNode.ts:138:70)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (EllipticalOrbit.ts:117:24)
at update (EllipticalOrbit.ts:72:15)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 5:50:03 PM

----------------------------------

my-solar-system : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661306274737%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at minus (EllipticalOrbitNode.ts:138:70)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (EllipticalOrbit.ts:117:24)
at update (CommonModel.ts:146:16)
at update (CommonModel.ts:151:9)
at step (Sim.ts:443:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1018:30)
at stepSimulation (Sim.ts:1008:11)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 5:50:03 PM

----------------------------------

my-solar-system : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661318976542%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at minus (EllipticalOrbitNode.ts:138:70)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (EllipticalOrbit.ts:117:24)
at update (CommonModel.ts:146:16)
at update (CommonModel.ts:151:9)
at step (Sim.ts:443:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1018:30)
at stepSimulation (Sim.ts:1008:11)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 5:50:03 PM

----------------------------------

my-solar-system : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661298603378/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661298603378%22%2C%22timestamp%22%3A1661338942451%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at minus (EllipticalOrbitNode.ts:138:70)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (EllipticalOrbit.ts:117:24)
at update (CommonModel.ts:146:16)
at update (CommonModel.ts:151:9)
at step (Sim.ts:443:21)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1018:30)
at stepSimulation (Sim.ts:1008:11)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 5:50:03 PM
```

**Comment by AgustinVallejo** [comment]
I believe this was fixed
