### ISSUE TITLE
CT 2 problems found.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#146]
```
my-solar-system : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Fatal error: tsc failed with code: 2
stdout:
js/intro/model/IntroModel.ts(34,7): error TS2741: Property 'index' is missing in type '{ active: true; mass: number; position: Vector2; velocity: Vector2; }' but required in type 'BodyInfo'.
js/intro/model/IntroModel.ts(35,7): error TS2741: Property 'index' is missing in type '{ active: true; mass: number; position: Vector2; velocity: Vector2; }' but required in type 'BodyInfo'.

2 problems found.

stderr:

Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681120366394%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681127546380%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681126298908%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : fuzz : unbuilt : listenerOrderRandom
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681121041184%7D&brand=phet&ea&fuzz&listenerOrder=random&memoryLimit=1000
Query: brand=phet&ea&fuzz&listenerOrder=random&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : fuzz : unbuilt : listenerOrderRandom
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681127909545%7D&brand=phet&ea&fuzz&listenerOrder=random&memoryLimit=1000
Query: brand=phet&ea&fuzz&listenerOrder=random&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681119971458%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681127447991%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681128785354%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681120320667%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM

----------------------------------

my-solar-system : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1681117746869/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1681117746869%22%2C%22timestamp%22%3A1681128253294%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
TypeError: Cannot read properties of undefined (reading 'isActiveProperty')
at isActiveProperty (SolarSystemCommonModel.ts:234:34)
at Array.forEach
at forEach (SolarSystemCommonModel.ts:231:15)
at loadBodyStates (IntroModel.ts:33:9)
at reset (SolarSystemCommonScreenView.ts:209:14)
at passedInListener (ResetAllButton.ts:72:26)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 4/10/2023, 3:09:06 AM
```

**Comment by veillette** [comment]
I believe this was addressed in #145.  CT is currently fine.
