### ISSUE TITLE
CT tried to removeListener on something that wasn't a listener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#190]
```
my-solar-system : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/phet-io-wrappers/state/?sim=my-solar-system&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694190103765%22%2C%22timestamp%22%3A1694192872698%7D
Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/assert/js/assert.js:28:13)
at assert (TinyEmitter.ts:174:6)
at removeListener (SVGGradientStop.ts:84:29)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:363:46)
at listener (PropertyStateHandler.ts:273:40)
at attemptToApplyPhases (PropertyStateHandler.ts:193:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:88:11)
at listener (TinyEmitter.ts:123:8)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1694190103765%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dmy-solar-system%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694190103765%22%2C%22timestamp%22%3A1694192872698%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1694190103765%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dmy-solar-system%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694190103765%22%2C%22timestamp%22%3A1694192872698%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/phet-io-wrappers/state/?sim=my-solar-system&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694190103765%22%2C%22timestamp%22%3A1694192872698%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/my-solar-system/my-solar-system_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=my-solar-system&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694190103765%22%2C%22timestamp%22%3A1694192872698%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/my-solar-system/my-solar-system_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=my-solar-system&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694190103765%22%2C%22timestamp%22%3A1694192872698%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: tried to removeListener on something that wasn't a listener
[PAGE ERROR] Error: Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/assert/js/assert.js:28:13)
at TinyEmitter.removeListener (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/TinyEmitter.js:144:7)
at SVGGradientStop.onPropertyChange (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/scenery/js/display/SVGGradientStop.js:60:30)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at ProfileColorProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/ReadOnlyProperty.js:284:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[PAGE ERROR] Error: Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/assert/js/assert.js:28:13)
at TinyEmitter.removeListener (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/TinyEmitter.js:144:7)
at SVGGradientStop.onPropertyChange (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/scenery/js/display/SVGGradientStop.js:60:30)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at ProfileColorProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/ReadOnlyProperty.js:284:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1694190103765/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 9/8/2023, 10:21:43 AM
```

**Comment by jonathanolson** [comment]
I believe the above workaround should fix this issue. @KatieWoe let's see if it goes away (it does in local testing)?

**Comment by KatieWoe** [comment]
Looks ok on CT

**Comment by pixelzoom** [comment]
There's no evidence of this on CT. It looks like this was fixed, but there was no followup.  So I'm going to close this issue.
