### ISSUE TITLE
CT If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#23]
```
my-solar-system : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664180628974/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1664180628974%22%2C%22timestamp%22%3A1664187121637%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664180628974/assert/js/assert.js:28:13)
at assert (Node.ts:2809:14)
at auditMaxDimensions (WidthSizable.ts:205:44)
at listener (TinyEmitter.ts:95:8)
at emit (TinyProperty.ts:129:9)
at notifyListeners (TinyProperty.ts:77:11)
at set (TinyProperty.ts:63:9)
at (WidthSizable.ts:124:6)
at (LayoutProxy.ts:438:4)
at (Checkbox.ts:323:6)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 2:23:48 AM

----------------------------------

my-solar-system : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664180628974/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1664180628974%22%2C%22timestamp%22%3A1664194741431%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664180628974/assert/js/assert.js:28:13)
at assert (Node.ts:2809:14)
at auditMaxDimensions (WidthSizable.ts:205:44)
at listener (TinyEmitter.ts:95:8)
at emit (TinyProperty.ts:129:9)
at notifyListeners (TinyProperty.ts:77:11)
at set (TinyProperty.ts:63:9)
at (WidthSizable.ts:124:6)
at (LayoutProxy.ts:438:4)
at (Checkbox.ts:323:6)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 2:23:48 AM
```

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/tasks/issues/1106, with ?stringTest=long, the sim looks like this:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/679486/194713401-0cd72b64-dd76-4c09-9213-4b002c166dae.png">

So it seems like adding some `maxWidth` on other text parts would help.

I also experimented with this workaround, but didn't feel confident about it at all.

<details>

```diff

Index: js/Checkbox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Checkbox.ts b/js/Checkbox.ts
--- a/js/Checkbox.ts	(revision 15be3e7ec7b6b9ad89936a0f6ecdbf2e23885ea9)
+++ b/js/Checkbox.ts	(date 1665240508301)
@@ -320,7 +320,11 @@
 
     // Attempt to set a preferredWidth
     if ( isWidthSizable( this.content ) ) {
-      contentProxy.preferredWidth = preferredWidth - checkboxWithoutSpacingWidth - this.options.spacing;
+      let pref = preferredWidth - checkboxWithoutSpacingWidth - this.options.spacing;
+      if ( this.content.maxWidth ) {
+        pref = Math.min( pref, this.content.maxWidth );
+      }
+      contentProxy.preferredWidth = pref;
     }
 
     // For now just position content. Future updates could include widthResizable content?

```

</details>

**Comment by KatieWoe** [comment]
Not sure if this is related:
```
my-solar-system : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665407749967/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665407749967%22%2C%22timestamp%22%3A1665412765553%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at minus (EllipticalOrbitNode.ts:144:70)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (EllipticalOrbit.ts:117:24)
at update (CommonModel.ts:216:16)
at update (CommonModel.ts:201:9)
at restart (CommonScreenView.ts:105:37)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (PushButtonModel.ts:179:22)
id: Bayes Puppeteer
Snapshot from 10/10/2022, 7:15:49 AM

----------------------------------

my-solar-system : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665407749967/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1665407749967%22%2C%22timestamp%22%3A1665414279134%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665407749967/assert/js/assert.js:28:13)
at assert (Node.ts:2809:14)
at auditMaxDimensions (WidthSizable.ts:205:44)
at listener (TinyEmitter.ts:95:8)
at emit (TinyProperty.ts:129:9)
at notifyListeners (TinyProperty.ts:77:11)
at set (TinyProperty.ts:63:9)
at (WidthSizable.ts:124:6)
at (LayoutProxy.ts:438:4)
at (Checkbox.ts:323:6)
id: Bayes Puppeteer
Snapshot from 10/10/2022, 7:15:49 AM
```
