### ISSUE TITLE
BodySoundManager.playBodyRemovedSound fails

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#290]
Related to #289 ...

Go to phetmarks and start the sim in the State wrapper.  It fails immediately with:

```
PhetioStateEngine.ts:329 Uncaught TypeError: Cannot read properties of undefined (reading 'play')
    at BodySoundManager.playBodyRemovedSound (BodySoundManager.ts:71:42)
    at LabScreenView.ts:39:31
    at TinyEmitter.emit (TinyEmitter.ts:123:9)
    at Emitter.emit (Emitter.ts:61:22)
    at createObservableArray.ts:214:86
    at Array.forEach (<anonymous>)
    at Object.set (createObservableArray.ts:214:44)
    at Proxy.applyState (createObservableArray.ts:445:51)
    at Object.applyState (createObservableArray.ts:487:172)
    at IOType.applyState (IOType.ts:308:17)
```

The relevant code in BodySoundManager.ts is:

```ts
  public playBodyRemovedSound( bodyNumber: number ): void {
    this.removalSoundClips[ bodyNumber ].play();
  }
```

... where `this.removalSoundClips[ bodyNumber ]` is returning `undefined`.

I don't understand why this is failing only in the State wrapper.

**Comment by pixelzoom** [comment]
In the above commit, I added assertions to get more information.  Here's what I see now:

```
Uncaught Error: Assertion failed: No soundClip found for bodyNumber -1
    at window.assertions.assertFunction (assert.js:28:13)
    at BodySoundManager.playBodyRemovedSound (BodySoundManager.ts:74:15)
    at LabScreenView.ts:39:31
```

**Comment by pixelzoom** [comment]
After changes in #291, the assertion message is now:

```
Uncaught Error: Assertion failed: No soundClip found for numberOfBodies 0
    at window.assertions.assertFunction (assert.js:28:13)
    at BodySoundManager.playBodyRemovedSound (BodySoundManager.ts:78:15)
    at LabScreenView.ts:39:31
```

The sole call to `playBodyRemovedSound` is in LabScreenView:

```ts
    model.activeBodies.addItemRemovedListener( () => {
      if ( !model.isAnyBodyCollidedProperty.value ) {
        this.bodySoundManager.playBodyRemovedSound( model.activeBodies.length );
      }
    } );
```

`model.activeBodies` is an ObservableArray. I'm guessing that the array contents are being restored before the array's `lengthProperty` is restored.  So this probably needs short-circuited when restoring state.  That is typically done by surrounding the problematic code with `if ( !isSettingPhetioStateProperty.value ) `.

**Comment by pixelzoom** [comment]
Fixed in the above commit by adding `if ( !isSettingPhetioStateProperty.value )` guards.

@AgustinVallejo FYI, this probably the most common type of problem that occurs in the State wrapper, and the typical way that it's addressed.  So please take a close look at this issue and the solution, ask questions, etc.   Happy to discuss on Zoom.  Or if it's crystal clear to you, feel free to close.
