### ISSUE TITLE
CT  Cannot read properties of undefined (reading 'minus')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#30]
```
my-solar-system : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at c (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:4253117)
at s.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:21425)
at l.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:6399)
at kw.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:4230922)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:4233458)
at o.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:21425)
at m._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:16023)
at m.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:15523)
at m.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:15327)
at m.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/build/phet/my-solar-system_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667827824919%7D&fuzz&memoryLimit=1000:963:13089)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 4:07:38 AM

----------------------------------

my-solar-system : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667828761146%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
TypeError: Cannot read properties of undefined (reading 'minus')
at minus (EllipticalOrbitNode.ts:144:70)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (EllipticalOrbit.ts:117:24)
at update (KeplersLawsModel.ts:61:20)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 4:07:38 AM

----------------------------------

my-solar-system : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667828720396%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=4, oldValue=5
Error: Assertion failed: reentry detected, value=4, oldValue=5
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (Slider.ts:420:24)
at _dragListener (PressListener.ts:528:9)
at call (DragListener.ts:309:35)
at apply (PhetioAction.ts:124:16)
at execute (DragListener.ts:460:21)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 4:07:38 AM

----------------------------------

my-solar-system : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667822135107%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/assert/js/assert.js:28:13)
at assert (Node.ts:2802:14)
at auditMaxDimensions (WidthSizable.ts:220:44)
at listener (TinyEmitter.ts:95:8)
at emit (TinyProperty.ts:129:9)
at notifyListeners (TinyProperty.ts:77:11)
at set (TinyProperty.ts:63:9)
at (WidthSizable.ts:134:39)
at (LayoutProxy.ts:438:52)
at (Checkbox.ts:330:33)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 4:07:38 AM
```

**Comment by AgustinVallejo** [comment]
This was because bodies were being put in the same place. They now collide.
