### ISSUE TITLE
CT Arc startAngle should be a finite number: NaN

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#39]
```
my-solar-system : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1669065011737%22%2C%22timestamp%22%3A1669067588526%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Arc startAngle should be a finite number: NaN
Error: Assertion failed: Arc startAngle should be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/assert/js/assert.js:28:13)
at assert (EllipticalArc.ts:356:14)
at invalidate (EllipticalArc.ts:86:9)
at (Shape.js:694:26)
at ellipticalArcPoint (Shape.js:672:16)
at ellipticalArc (EllipticalOrbitNode.ts:157:68)
at Array.forEach
at forEach (EllipticalOrbitNode.ts:139:30)
at updatedOrbit (EllipticalOrbitNode.ts:172:12)
at callback (Multilink.ts:111:10)
id: Bayes Puppeteer
Snapshot from 11/21/2022, 2:10:11 PM

----------------------------------

my-solar-system : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1669065011737%22%2C%22timestamp%22%3A1669067595713%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Arc startAngle should be a finite number: NaN
Error: Assertion failed: Arc startAngle should be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/assert/js/assert.js:28:13)
at assert (EllipticalArc.ts:356:14)
at invalidate (EllipticalArc.ts:86:9)
at (Shape.js:694:26)
at ellipticalArcPoint (Shape.js:672:16)
at ellipticalArc (EllipticalOrbitNode.ts:157:68)
at Array.forEach
at forEach (EllipticalOrbitNode.ts:139:30)
at updatedOrbit (EllipticalOrbitNode.ts:172:12)
at callback (Multilink.ts:111:10)
id: Bayes Puppeteer
Snapshot from 11/21/2022, 2:10:11 PM

----------------------------------

my-solar-system : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1669065011737%22%2C%22timestamp%22%3A1669069509813%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Arc startAngle should be a finite number: NaN
Error: Assertion failed: Arc startAngle should be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/assert/js/assert.js:28:13)
at assert (EllipticalArc.ts:356:14)
at invalidate (EllipticalArc.ts:86:9)
at (Shape.js:694:26)
at ellipticalArcPoint (Shape.js:672:16)
at ellipticalArc (EllipticalOrbitNode.ts:157:68)
at Array.forEach
at forEach (EllipticalOrbitNode.ts:139:30)
at updatedOrbit (EllipticalOrbitNode.ts:172:12)
at callback (Multilink.ts:111:10)
id: Bayes Puppeteer
Snapshot from 11/21/2022, 2:10:11 PM

----------------------------------

my-solar-system : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1669065011737%22%2C%22timestamp%22%3A1669068483008%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Arc startAngle should be a finite number: NaN
Error: Assertion failed: Arc startAngle should be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669065011737/assert/js/assert.js:28:13)
at assert (EllipticalArc.ts:356:14)
at invalidate (EllipticalArc.ts:86:9)
at (Shape.js:694:26)
at ellipticalArcPoint (Shape.js:672:16)
at ellipticalArc (EllipticalOrbitNode.ts:157:68)
at Array.forEach
at forEach (EllipticalOrbitNode.ts:139:30)
at updatedOrbit (EllipticalOrbitNode.ts:172:12)
at callback (Multilink.ts:111:10)
id: Bayes Puppeteer
Snapshot from 11/21/2022, 2:10:11 PM
```

**Comment by AgustinVallejo** [comment]
This is on Kepler's Laws Screen, so doesn't count for Dev Test :) still, looking into reproducing and fixing
