### ISSUE TITLE
CT: max > min required for moduloBetween

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#80]
This happened 2x yesterday 1/19, has not happened on 1/20.  Perhaps it was a transisent problem. But just in case...

```
my-solar-system : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674172375669/my-solar-system/my-solar-system_en.html?continuousTest=%7B%22test%22%3A%5B%22my-solar-system%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674172375669%22%2C%22timestamp%22%3A1674177051320%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: max > min required for moduloBetween
Error: Assertion failed: max > min required for moduloBetween
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674172375669/assert/js/assert.js:28:13)
at assert (Utils.js:57:14)
at moduloBetweenDown (EllipticalOrbitEngine.ts:220:29)
at Array.forEach
at forEach (EllipticalOrbitEngine.ts:211:22)
at calculateOrbitalDivisions (EllipticalOrbitEngine.ts:174:11)
at update (EllipticalOrbitEngine.ts:119:13)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
id: Bayes Puppeteer
Snapshot from 1/19/2023, 4:52:55 PM
```

**Comment by AgustinVallejo** [comment]
I believe this was fixed, if it happens again, it should be issued to Kepler's Laws sim:
https://github.com/phetsims/keplers-laws/issues
